class Imprimir:
    def desenharNaTela(self, nErros):
        self.nErros = nErros

        if(self.nErros == 0):
            print("")
            print("|||||||||||||  " )
            print("++              ")
            print("++              ")
            print("++              ")
            print("++              ")
            print("++              ")
            print("++              ")
            print("++              ")
            print("++              ")
            print("++              ")
            print("++              ")
            print("++              ")
            print("++              ")
            print("")

        if(self.nErros == 1):
            print("")
            print("|||||||||||||  " )
            print("++         ***  ")
            print("++        *   * ")
            print("++         ***  ")
            print("++              ")
            print("++              ")
            print("++              ")
            print("++              ")
            print("++              ")
            print("++              ")
            print("++              ")
            print("++              ")
            print("++              ")
            print("")
        
        if(self.nErros == 2):
            print("")
            print("|||||||||||||  " )
            print("++         ***  ")
            print("++        *   * ")
            print("++         ***  ")
            print("++          |   ")
            print("++          |   ")
            print("++          |   ")
            print("++          |   ")
            print("++              ")
            print("++              ")
            print("++              ")
            print("++              ")
            print("++              ")
            print("")
        
        if(self.nErros == 3):
            print("")
            print("|||||||||||||  " )
            print("++         ***  ")
            print("++        *   * ")
            print("++         ***  ")
            print("++         /|   ")
            print("++        / |   ")
            print("++          |   ")
            print("++          |   ")
            print("++              ")
            print("++              ")
            print("++              ")
            print("++              ")
            print("++              ")
            print("")
        
        if(self.nErros == 4):
            print("")
            print("|||||||||||||  " )
            print("++         ***  ")
            print("++        *   * ")
            print("++         ***  ")
            print("++         /|\  ")
            print("++        / | \ ")
            print("++          |   ")
            print("++          |   ")
            print("++              ")
            print("++              ")
            print("++              ")
            print("++              ")
            print("++              ")
            print("")

        if(self.nErros == 5):
            print("")
            print("|||||||||||||  " )
            print("++         ***  ")
            print("++        *   * ")
            print("++         ***  ")
            print("++         /|\  ")
            print("++        / | \ ")
            print("++          |   ")
            print("++          |   ")
            print("++         /    ")
            print("++        /     ")
            print("++              ")
            print("++              ")
            print("++              ")
            print("")
        
        if(self.nErros == 6):
            print("")
            print("|||||||||||||  " )
            print("++         ***  ")
            print("++        *   * ")
            print("++         ***  ")
            print("++         /|\  ")
            print("++        / | \ ")
            print("++          |   ")
            print("++          |   ")
            print("++         / \  ")
            print("++        /   \ ")
            print("++              ")
            print("++              ")
            print("++              ")
            print("")