class Imprimir:
    def desenharNaTela(self, nErros):
        self.nErros = nErros

        if(self.nErros == 0):
            print("")
            print("  |||||||||||||  " )
            print("  ++              ")
            print("  ++              ")
            print("  ++              ")
            print("  ++              ")
            print("  ++              ")
            print("  ++              ")
            print("  ++              ")
            print("  ++              ")
            print("  ++              ")
            print("  ++              ")
            print("  ++              ")
            print("  ++              ")
            print(" ++++             ")
            print("++++++            ")
            print("")

        elif(self.nErros == 1):
            print("")
            print("  |||||||||||||  " )
            print("  ++         ***  ")
            print("  ++        *   * ")
            print("  ++         ***  ")
            print("  ++              ")
            print("  ++              ")
            print("  ++              ")
            print("  ++              ")
            print("  ++              ")
            print("  ++              ")
            print("  ++              ")
            print("  ++              ")
            print("  ++              ")
            print(" ++++             ")
            print("++++++            ")
            print("")
        
        elif(self.nErros == 2):
            print("")
            print("  |||||||||||||  " )
            print("  ++         ***  ")
            print("  ++        *   * ")
            print("  ++         ***  ")
            print("  ++          |   ")
            print("  ++          |   ")
            print("  ++          |   ")
            print("  ++          |   ")
            print("  ++              ")
            print("  ++              ")
            print("  ++              ")
            print("  ++              ")
            print("  ++              ")
            print(" ++++             ")
            print("++++++            ")
            print("")
        
        elif(self.nErros == 3):
            print("")
            print("  |||||||||||||  " )
            print("  ++         ***  ")
            print("  ++        *   * ")
            print("  ++         ***  ")
            print("  ++         /|   ")
            print("  ++        / |   ")
            print("  ++          |   ")
            print("  ++          |   ")
            print("  ++              ")
            print("  ++              ")
            print("  ++              ")
            print("  ++              ")
            print("  ++              ")
            print(" ++++             ")
            print("++++++            ")
            print("")
        
        elif(self.nErros == 4):
            print("")
            print("  |||||||||||||  " )
            print("  ++         ***  ")
            print("  ++        *   * ")
            print("  ++         ***  ")
            print("  ++         /|\  ")
            print("  ++        / | \ ")
            print("  ++          |   ")
            print("  ++          |   ")
            print("  ++              ")
            print("  ++              ")
            print("  ++              ")
            print("  ++              ")
            print("  ++              ")
            print(" ++++             ")
            print("++++++            ")
            print("")

        elif(self.nErros == 5):
            print("")
            print("  |||||||||||||  " )
            print("  ++         ***  ")
            print("  ++        *   * ")
            print("  ++         ***  ")
            print("  ++         /|\  ")
            print("  ++        / | \ ")
            print("  ++          |   ")
            print("  ++          |   ")
            print("  ++         /    ")
            print("  ++        /     ")
            print("  ++              ")
            print("  ++              ")
            print("  ++              ")
            print(" ++++             ")
            print("++++++            ")
            print("")
        
        else:
            print("")
            print("  |||||||||||||  " )
            print("  ++         ***  ")
            print("  ++        *   * ")
            print("  ++         ***  ")
            print("  ++         /|\  ")
            print("  ++        / | \ ")
            print("  ++          |   ")
            print("  ++          |   ")
            print("  ++         / \  ")
            print("  ++        /   \ ")
            print("  ++              ")
            print("  ++              ")
            print("  ++              ")
            print(" ++++             ")
            print("++++++            ")
            print("")